### ISSUE TITLE
Deprecated <<-EOS.undent

### ISSUE THREAD

**Issue by olivierlacan** [puma/homebrew-puma#5]
```
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/puma/homebrew-puma/puma-dev.rb:30:in `caveats'
Please report this to the puma/puma tap!
```
Gotta say I don't really know how to address this because `<<~` is [only available in Ruby 2.3](https://infinum.co/the-capsized-eight/multiline-strings-ruby-2-3-0-the-squiggly-heredoc) so it seems a bit wasteful to detect it or check the Ruby version just to avoid this warning.

**Comment by nonrational** [comment]
Homebrew [must be run under ruby 2.3](https://github.com/Homebrew/brew/blob/0cd50400c7c1727ec602a9f8dcdc08678622d61e/Library/Homebrew/brew.rb#L12) as of [~5 months ago](https://github.com/Homebrew/brew/commit/bcca2a7c6b80a6450bd8261af987a8da260b6b89), so seems to me like `<<~EOS` should be acceptable, yeah?

**Comment by rmm5t** [comment]
Plus, [Ruby 2.2 is end-of-lifed on March 31, 2018](https://www.ruby-lang.org/en/downloads/branches/).
